name: Ubuntu (latest)

on: [push]

permissions:
  contents: read

jobs:
  lint: # from lint.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linters.txt 
    - name: Lint with flake8
      run: |
        flake8 --show-source

  pytest-coverage: # from pytest_coverage.yml
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install -r requirements-test.txt
    - name: Test with pytest and report code coverage
      run: |
        coverage run -m pytest -rA
        coverage report
    
  
  interactive-kvasir: # from interactive-kvasir.yml
    needs: [lint, pytest-coverage, dockerization]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Interactive API - pytorch_kvasir_unet
      run: |
        pip install torch==1.13.1
        pip install torchvision==0.14.1
        cd test
        python test_algorithms.py